version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: client-maneger-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./apps/:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - clientManeger
    depends_on:
     - client-maneger-api
     - client-maneger-frontend

  client-maneger-api:
    build:
      args:
        user: guilherme
        uid: 1000
      context: ./apps/client-maneger-api
      dockerfile: Dockerfile
    image: client-maneger-api
    container_name: client-maneger-api
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./apps/client-maneger-api:/var/www/html/
    environment:
      - "SERVICE_NAME=backend"
      - "DB_PORT=3306"
      - "DB_HOST=client-maneger-db"
      - "DB_DATABASE=clientManeger"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
    depends_on:
      - db
    networks: 
      - clientManeger
      
  client-maneger-frontend:
    container_name: client-maneger-frontend
    build:
      context: ./apps/client-maneger-frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./apps/client-maneger-frontend:/var/www/html/
    networks:
      - clientManeger

  db:
    image: mariadb
    container_name: client-maneger-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

    networks:
      - clientManeger

networks:
  clientManeger:
    driver: bridge
